config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'chatroom#index'
  get '/login' => 'sessions#new'
  post '/signup' => 'sessions#sign_up'
  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#delete'

  post '/message' => 'messages#create'
  post '/specific_message' => 'messages#specific_message_create'

  get '/user/:friend_message_id' => 'chatroom#chat_a_friend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user_message, class_name: 'User'
  belongs_to :friend_message, class_name: 'User', optional: true

  # Returns a list of users @mentioned in message content.
  def mentions
    body.scan(/@(#{User::NAME_REGEX})/).flatten.map do |username|
      User.find_by(username: username)
    end.compact
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  NAME_REGEX = /\w+/.freeze
  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A#{NAME_REGEX}\z/i }

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  VALID_EMAIL =
    /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i.freeze

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL }, uniqueness: { case_sensitive: false }

  has_secure_password

  has_many :generals, foreign_key: 'user_message_id', class_name: 'Message', dependent: :destroy
  has_many :user_messages, through: :generals

  has_many :specifics, foreign_key: 'friend_message_id', class_name: 'Message', dependent: :destroy
  has_many :friend_messages, through: :specifics

  has_one_attached :image
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :redirect
  include SessionsHelper

  private

  def require_login
    unless logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end

  def redirect
    redirect_to root_path
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  include MessageHelper
  before_action :require_login

  def index
    @users = User.where('id != ?', session[:user_id])
    @message = Message.new
    # @messages = Message.where('friend_message_id is null').includes(:user_message, :friend_message)
    @messages = fetch_all_messages_redis
  
  end

  def chat_a_friend
    @users = User.where('id != ?', session[:user_id])
    @message = Message.new(friend_message_id: params[:user_id])
    @messages = fetch_specific_messages_redis
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :require_login

  def create
    message = Message.create(body: params[:message][:body], user_message_id: session[:user_id])
    ActionCable.server.broadcast 'chatroom_channel',
                                 message: message_render(message)
    if message.mentions
      message.mentions.each do |mention|
        ActionCable.server.broadcast "chatroom_channel_for_user_#{mention.id}",
                                    mention: true
      end
    end
  rescue ActiveRecord::RecordNotSaved
    redirect_to root_path
  end

  def specific_message_create
    message = Message.create(body: params[:message][:body], user_message_id: session[:user_id],
                             friend_message_id: params[:message][:friend_message_id])
    ActionCable.server.broadcast 'chatroom_channel',
                                 message: message_render(message)
  rescue ActiveRecord::RecordNotSaved
    redirect_to root_path
  end

  private

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: %i[new create]

  def new; end

  def sign_up
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:info] = 'Account created successfully'
      redirect_to root_url
    else
      redirect_to login_url
    end
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user.blank?
      flash.now[:warning] = 'You need to create an account'
      redirect_to login_url
    elsif @user&.authenticate(params[:session][:password])
      log_in @user
      flash[:success] = 'Welcome back'
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def delete
    log_out
    redirect_to login_path
  end

  private

  def user_params
    if params[:session][:email]
      {
        username: params[:session][:username],
        email: params[:session][:email],
        password: params[:session][:password],
        image: params[:session][:image]
      }
    else
      {
        username: params[:session][:username],
        password: params[:session][:password]
      }
    end
  end

  def redirect_if_logged_in
    if logged_in?
      flash[:error] = 'Your are already logged in'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/chatroom_helper.rb
# frozen_string_literal: true

module ChatroomHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def fetch_all_messages_redis
    messages = Marshal.load($redis.get('messages'))  rescue nil # This line requests redis-server to accepts any value associate with messages key
    if messages.nil? # this condition will executes if any messages not available on redis server
      messages = Message.where('friend_message_id is null').includes(:user_message, :friend_message)
      $redis.set('messages', Marshal.dump(messages))
      $redis.expire('messages', 1.hour.to_i)
    end
    messages
  end

  def fetch_specific_messages_redis
    friend_messages = Marshal.load($redis.get('friend_messages')) rescue nil  # This line requests redis-server to accepts any value associate with messages key
    if friend_messages.nil? # this condition will executes if any messages not available on redis server
      friend_messages = Message.where("user_message_id = ? AND friend_message_id = ? OR
        user_message_id = ? AND friend_message_id = ? ",
                               session[:user_id], params[:friend_message_id],
                               params[:friend_message_id], session[:user_id]).includes(:user_message, :friend_message)
      $redis.set('friend_messages', Marshal.dump(friend_messages))
      $redis.expire('friend_messages', 1.hour.to_i)
    end
    friend_messages
  end

  def markdown_to_html(text)
    if text.nil?
      return
    end
    Kramdown::Document.new(text, input: 'GFM').to_html
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    cookies[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.blank?
  end

  def log_out
    session.delete(:user_id)
    cookies.delete(:user_id)
    @current_user = nil
  end
end

app/views/chatroom/chat_a_friend.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange  users icon"></i>
  Let's Chat
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%=  render @messages %>
        </div>
      </div>
      <div class="extra content content-height">
        <%= form_for(@message, html: {class: 'ui reply form'}, url: specific_message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui  fluid icon input">
              <%= f.text_area :body, placeholder: "Enter a message...", required: :true, class: 'message_body', cols: 2, rows: 1 %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
              <%= f.hidden_field :friend_message_id, :value => params[:friend_message_id] %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
       <h4>Users</h4>
        <div class="ui inverted vertical menu username-field">
         <% @users.map do |user| %>
          <a class="active item user-name" href="/user/<%= user.id %>" >
           <%= user.username %>
          </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange  users icon"></i>
  Let's Chat
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%=  render @messages %>
        </div>
      </div>
      <div class="extra content content-height">
        <%= form_for(@message, html: {class: 'ui reply form'}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui  fluid icon input">
              <%= f.text_area :body, placeholder: "Enter a message...", required: :true, class: 'message_body', cols: 2, rows: 1 %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
       <h4>Users</h4>
        <div class="ui inverted vertical menu username-field">
          
         <% @users.map do |user| %>
          <a class="active item user-name">
           <%= user.username %>
          </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="ui container">
  <%= link_to 'Chatroom', root_path, class: "item" %>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
        <% if logged_in? %>
          <%= link_to 'Log out',logout_path, method: :delete, class: "item" %>
        <% else %>
          <%= link_to 'Log in', login_path, class: "item" %>
        <% end%>
      </div>
    </div>
    <div class="item">
      <% if !logged_in? %>
      <%= link_to 'Sign up', login_path, class: "ui primary button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewDesignChatApp</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="ui small  inverted menu">
    <%= render 'layouts/header' %>
  </div>
  <body>
    <div class="ui container">
      <%= custom_bootstrap_flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<% if session[:user_id]  == message.user_message_id %>
  <div class="user-chat-message event chat-message">
    <div class="content message-flex">
      <div class="current-chat-username">
        <%= current_user.username %>
      </div>
      <div class="summary">
        <%= sanitize markdown_to_html(message.body) %>
      </div>
    </div>
    <%= image_tag current_user.image, class: "ui medium circular image oval" %>
  </div>
<% else %>
  <div class="event chat-message">
    <%= image_tag message.user_message.image, class: "ui medium circular image oval" %>
    <div class="content message-flex">
      <div class="non-current-chat-username">
        <%= message.user_message.username %>
      </div>
      <div class="summary">
        <%= sanitize markdown_to_html(message.body) %>
      </div>
    </div>
  </div>
<% end %>